fix(insights): update insights example for Vue InstantSearch
algolia/doc-code-samples pull request #242
Opened 2021-04-22 16:39 UTC by eunjae-lee

## Summary

This PR updates the insights example for Vue InstantSearch.
It's using the temporary build from CodeSandbox, so this shouldn't be merged until we release the latest version of Vue InstantSearch.

2021-04-27 08:56 UTC, tkrugg requested changes
All good, other than the init call needs to be restored if my understand is correct

2021-04-27 15:42 UTC, eunjae-lee commented on Vue InstantSearch/algolia-insights/public/index.html
> -      })
No, actually `insights` middleware calls `init`, so it's no longer needed :)

2021-04-27 15:55 UTC, tkrugg commented on Vue InstantSearch/algolia-insights/public/index.html
> -      })
Oh I didn't know that. I've tested the code and I see the following error. Is there an examplanation for it?



![2021-04-27 17 54 20](https://user-images.githubusercontent.com/2982512/116273002-ae310500-a781-11eb-9d49-3a43b86aa648.gif)

codesandbox: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/fix/insights-vue/Vue%20InstantSearch/algolia-insights?file=/public/index.html

2021-04-28 12:56 UTC, eunjae-lee commented on Vue InstantSearch/algolia-insights/public/index.html
> -      })
I'm not 100% sure, but I feel like it's a bug from CodeSandbox.
When I managed to reproduce the issue, [the constructor of AlgoliaAnalytics](https://github.com/algolia/search-insights.js/blob/master/lib/insights.ts#L127) was called twice. It shouldn't, right?

So, the second call overwrites and the initialization is gone, so we see that error message. I downloaded the project, ran locally and it worked well.

https://user-images.githubusercontent.com/499898/116407189-cceed480-a831-11eb-9ebf-8b0ea0d98100.mp4

I'll check with CodeSandbox support.

2021-05-18 09:01 UTC, eunjae-lee commented on Vue InstantSearch/algolia-insights/public/index.html
> -      })
@tkrugg It seems it's fixed on CodeSandbox' side. The link above no longer gives the error.

2021-05-19 08:23 UTC, eunjae-lee commented
[Not urgent] Can I have your reviews here? @shortcuts @Haroenv

2021-05-19 11:51 UTC, Haroenv commented on Vue InstantSearch/algolia-insights/public/index.html
> +      var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@1.7.1";
v2 now?

2021-05-19 14:17 UTC, Haroenv reviewed
looks good otherwise, has the doc been updated to match this?

2021-05-19 14:17 UTC, Haroenv commented on Vue InstantSearch/algolia-insights/public/index.html
> +      var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@2";
```suggestion
      var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@2.0.0";
```

2021-05-20 08:35 UTC, eunjae-lee commented
> looks good otherwise, has the doc been updated to match this?

yeah actually the doc is already up-to-date!
https://www.algolia.com/doc/guides/building-search-ui/going-further/send-insights-events/vue/

2021-05-20 09:56 UTC, Haroenv approved these changes

2021-05-20 13:55 UTC, merged